# Generated by Django 5.2.7 on 2025-11-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField(help_text="Сумма в рублях")),
                ("currency", models.CharField(default="rub", max_length=10)),
                ("stripe_product_id", models.CharField(blank=True, max_length=255, null=True)),
                ("stripe_price_id", models.CharField(blank=True, max_length=255, null=True)),
                ("stripe_session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("stripe_session_url", models.URLField(blank=True, null=True)),
                ("status", models.CharField(default="создан", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="платежи", to="materials.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="платежи",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
