# Generated by Django 5.2.7 on 2025-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
